# Taken from http://stackoverflow.com/a/16751773/329700 

language: objective-c

env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VERSION="3.2.5"

before_install:
 - wget "http://download.xamarin.com/MonoFrameworkMDK/Macx86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

script:
 - cat /Users/travis/build/twilio/twilio-csharp/src/.nuget/nuget.targets
 - cd src/Twilio.Api && xbuild /p:TargetFrameworkProfile=""
 - find . -name '*.dll'
 - .ci/nunit.sh src/Twilio.Api.Tests.Integration
